name: alexchen2
favicon: null
layout_spectrum: 0.4154499424621463
typography_spectrum: 0.8120230485219508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.3256974483374506
purpose: []
